pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "dockerjenkinsmicroservice:latest"
        CONTAINER_NAME = "dockerjenkinsmicroservice"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/LinuxTute-GitHub/lake.git', branch: 'microservice'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "cd microservice && docker build -t $DOCKER_IMAGE ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh '''
                    docker run -d -p 8080:8080 -d  $DOCKER_IMAGE
                    '''
                }
            }
        }
    }
}

