pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "dockernodejs:latest"
        CONTAINER_NAME = "dockernodejs"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/LinuxTute-GitHub/lake.git', branch: 'node'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "cd node && docker build -t $DOCKER_IMAGE ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh '''
                    docker run -itd -p 3000:3000  $DOCKER_IMAGE
                    '''
                }
            }
        }
    }
}

