pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "dockerwebapp:latest"
        CONTAINER_NAME = "dockerwebapp"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/LinuxTute-GitHub/lake.git', branch: 'webapp'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "cd webapp && docker build -t $DOCKER_IMAGE ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh '''
                    docker run -itd -p 9000:9000  $DOCKER_IMAGE
                    '''
                }
            }
        }
    }
}

